import { createRoot } from 'react-dom/client'
import { useEffect, useState } from 'react'
import { api } from './services/api'
import './styles.css'

const nav = [['/', 'NFL Dashboard'], ['/predictions', 'NFL Predictions'], ['/elo-ratings', 'NFL Elo Ratings'], ['/touchdowns', 'Touchdown Predictions'], ['/first-touchdowns', 'First TD Predictions'], ['/touchdown-history', 'NFL Touchdown History'], ['/nfl-players', 'NFL Player Stats'], ['/performance', 'NFL Performance'], ['/history', 'NFL History'], ['/cfb', 'CFB Totals'], ['/cfb-history', 'CFB Totals History'], ['/mlb-games', 'MLB Game Predictions'], ['/mlb', 'MLB Operations'], ['/mlb-history', 'MLB History'], ['/methodology', 'Methodology']]
const pct = value => value == null ? '—' : `${(value * 100).toFixed(1)}%`
const margin = value => value == null ? '—' : `${value > 0 ? '+' : ''}${Number(value).toFixed(1)}`
const teamLine = (value, game, market = false) => {
  if (value == null || !game) return '—'
  const homeMargin = market ? -value : value
  const team = homeMargin >= 0 ? game.home_team : game.away_team
  return `${team} -${Math.abs(homeMargin).toFixed(1)}`
}
const disagreement = (value, game) => {
  if (value == null || !game) return '—'
  const team = value >= 0 ? game.home_team : game.away_team
  return `${Math.abs(value).toFixed(1)} pts → ${team}`
}
const easternTime = value => value == null ? '—' : new Date(value).toLocaleString('en-US', { timeZone: 'America/New_York', dateStyle: 'short', timeStyle: 'short' }) + ' ET'

function useData(path) {
  const [state, setState] = useState({ loading: true, data: null, error: null })
  useEffect(() => { let active = true; api(path).then(data => active && setState({ loading: false, data, error: null })).catch(error => active && setState({ loading: false, data: null, error })); return () => { active = false } }, [path])
  return state
}

function Empty({ children }) { return <div className="empty">{children}</div> }
function Loading() { return <Empty>Loading model data…</Empty> }

function PredictionTable({ predictions, games = [] }) {
  if (!predictions.length) return <Empty>No published predictions yet.</Empty>
  const gameById = Object.fromEntries(games.map(game => [game.id, game]))
  return <div className="table-wrap"><table><thead><tr><th>Matchup</th><th>Model win %</th><th>Market win %</th><th>Difference</th><th>Model line</th><th>Market line</th><th>Model disagreement</th></tr></thead><tbody>{predictions.map(prediction => { const game = gameById[prediction.game_id]; return <tr key={prediction.id}><td>{game ? <a href={`/games/${game.id}`}>{game.away_team} @ {game.home_team}</a> : prediction.game_id}</td><td>{pct(prediction.home_win_probability)}</td><td>{pct(prediction.market_home_probability)}</td><td className="accent">{pct(prediction.moneyline_difference)}</td><td>{teamLine(prediction.predicted_margin, game)}</td><td>{teamLine(prediction.market_spread, game, true)}</td><td className="accent">{disagreement(prediction.spread_difference, game)}</td></tr> })}</tbody></table></div>
}

function Dashboard() { const games = useData('/games/current-week'); const predictions = useData('/predictions/current-week'); if (games.loading || predictions.loading) return <Loading />; if (games.error || predictions.error) return <Empty>Backend unavailable. Start FastAPI on port 8000.</Empty>; return <><section className="hero"><p className="eyebrow">NFL QUANTITATIVE GAME MODEL</p><h1>Current-week projections</h1><p>Pregame model probabilities and market comparison. Results are analytical projections, not guarantees.</p></section><div className="stat-grid"><div><b>{games.data.length}</b><span>Upcoming games</span></div><div><b>{predictions.data.length}</b><span>Published projections</span></div><div><b>V0.1</b><span>Model release</span></div></div><PredictionTable predictions={predictions.data} games={games.data} /></> }
function Predictions() { const predictions = useData('/predictions'); const games = useData('/games'); if (predictions.loading || games.loading) return <Loading />; return <><h1>Predictions</h1><p className="lede">Published model outputs, preserved with their original model version and timestamp.</p><PredictionTable predictions={predictions.data || []} games={games.data || []} /></> }
function Performance() { const data = useData('/performance'); if (data.loading) return <Loading />; if (data.error) return <Empty>Performance data is unavailable.</Empty>; const { moneyline, spread } = data.data; return <><h1>Historical performance</h1><div className="metric-grid"><article><p>Moneyline accuracy</p><b>{pct(moneyline.accuracy)}</b><small>{moneyline.games} graded games · Brier {moneyline.brier_score?.toFixed(3) ?? '—'}</small></article><article><p>Spread MAE</p><b>{spread.mae?.toFixed(2) ?? '—'}</b><small>{spread.games} graded games · RMSE {spread.rmse?.toFixed(2) ?? '—'}</small></article><article><p>ATS record</p><b>{spread.ats ? `${spread.ats.wins}-${spread.ats.losses}-${spread.ats.pushes}` : '—'}</b><small>ROI appears after linked live odds snapshots</small></article></div></> }
function History() { const history = useData('/predictions/history'); if (history.loading) return <Loading />; if (history.error) return <Empty>NFL history is unavailable.</Empty>; const { predictions, record } = history.data; return <><h1>NFL prediction history</h1><p className="lede">Every published model output remains visible after games finish.</p><div className="metric-grid"><article><p>Moneyline record</p><b>{record.wins}-{record.losses}-{record.pushes}</b><small>WIN · LOSS · PUSH</small></article></div>{predictions.length ? <div className="table-wrap"><table><thead><tr><th>Matchup</th><th>Game time</th><th>Model pick</th><th>Home win %</th><th>Result</th><th>Model</th></tr></thead><tbody>{predictions.map(prediction => <tr key={prediction.id}><td>{prediction.away_team} @ {prediction.home_team}</td><td>{easternTime(prediction.date)}</td><td className="accent">{prediction.home_win_probability >= .5 ? prediction.home_team : prediction.away_team}</td><td>{pct(prediction.home_win_probability)}</td><td>{prediction.result || 'Pending'}</td><td>{prediction.model_version}</td></tr>)}</tbody></table></div> : <Empty>No NFL prediction history yet.</Empty>}</> }
function EloRatings() { const data = useData('/elo-ratings'); if (data.loading) return <Loading />; if (data.error) return <Empty>NFL Elo ratings are unavailable.</Empty>; return <><section className="hero"><p className="eyebrow">NFL TEAM STRENGTH</p><h1>NFL Elo ratings</h1><p>Ratings update only after completed games are imported. Change shows the team’s movement from its most recent completed game.</p></section><div className="table-wrap"><table><thead><tr><th>Rank</th><th>Team</th><th>Elo rating</th><th>Last change</th><th>Current record</th></tr></thead><tbody>{data.data.ratings.map(row => <tr key={row.team}><td>{row.rank}</td><td className="accent">{row.team}</td><td>{row.rating.toFixed(1)}</td><td className={row.change >= 0 ? 'accent' : ''}>{row.change >= 0 ? '+' : ''}{row.change.toFixed(1)}</td><td>{row.wins}-{row.losses}-{row.ties}</td></tr>)}</tbody></table></div></> }
function TouchdownPredictions() { const data = useData('/touchdowns/current-week'); if (data.loading) return <Loading />; if (data.error) return <Empty>Touchdown predictions are unavailable. Train the TD model, then publish the current week’s active-roster picks.</Empty>; const predictions = data.data; const byGame = predictions.reduce((groups, pick) => ({ ...groups, [pick.game_id]: [...(groups[pick.game_id] || []), pick] }), {}); return <><section className="hero"><p className="eyebrow">NFL ANYTIME-TOUCHDOWN MODEL</p><h1>Touchdown predictions</h1><p>Active-roster, pregame anytime-TD probabilities. The score is each player’s percentile among this week’s eligible players—not a percent chance.</p></section>{predictions.length ? <><h2>Top 10 anytime-TD probabilities</h2><div className="table-wrap"><table><thead><tr><th>Rank</th><th>Player</th><th>Team</th><th>Matchup</th><th>Anytime TD</th><th>TD score</th><th>2+ TD call</th></tr></thead><tbody>{predictions.slice(0, 10).map((pick, index) => <tr key={pick.id}><td>{index + 1}</td><td>{pick.player_name}</td><td>{pick.team}</td><td>{pick.away_team} @ {pick.home_team}</td><td className="accent">{pct(pick.probability)}</td><td>{pick.td_score}/100</td><td>{pick.two_td_call ? `${pct(pick.two_td_probability)} model probability` : '—'}</td></tr>)}</tbody></table></div><h2>By matchup</h2>{Object.values(byGame).map(picks => <div className="method" key={picks[0].game_id}><h3>{picks[0].away_team} @ {picks[0].home_team} · {easternTime(picks[0].date)}</h3><div className="table-wrap"><table><thead><tr><th>Player</th><th>Team</th><th>Anytime TD</th><th>TD score</th><th>2+ TD</th></tr></thead><tbody>{picks.map(pick => <tr key={pick.id}><td>{pick.player_name}</td><td>{pick.team}</td><td className="accent">{pct(pick.probability)}</td><td>{pick.td_score}/100</td><td>{pick.two_td_call ? 'Model 2+ TD call' : '—'}</td></tr>)}</tbody></table></div></div>)}</> : <Empty>No current-week touchdown picks are published. Run the TD publisher after training; it uses the NFLverse active roster for that week.</Empty>}</> }
function TouchdownHistory() { const data = useData('/touchdowns/history'); if (data.loading) return <Loading />; if (data.error) return <Empty>Touchdown history is unavailable.</Empty>; const { predictions, record } = data.data; return <><h1>NFL touchdown history</h1><p className="lede">Every published anytime-TD pick is preserved and graded after its game is final.</p><div className="metric-grid"><article><p>Anytime-TD record</p><b>{record.hits}-{record.misses}</b><small>HIT · MISS</small></article><article><p>Accuracy</p><b>{pct(record.accuracy)}</b><small>Graded official predictions</small></article></div>{predictions.length ? <div className="table-wrap"><table><thead><tr><th>Player</th><th>Team</th><th>Matchup</th><th>Game time</th><th>Anytime TD</th><th>Score</th><th>Result</th><th>Model</th></tr></thead><tbody>{predictions.map(pick => <tr key={pick.id}><td>{pick.player_name}</td><td>{pick.team}</td><td>{pick.away_team} @ {pick.home_team}</td><td>{easternTime(pick.date)}</td><td>{pct(pick.probability)}</td><td>{pick.td_score}/100</td><td className={pick.result === 'HIT' ? 'accent' : ''}>{pick.result}</td><td>{pick.model_version}</td></tr>)}</tbody></table></div> : <Empty>No graded touchdown predictions yet.</Empty>}</> }
function FirstTouchdowns() { const current = useData('/first-touchdowns'); const history = useData('/first-touchdowns/history'); if (current.loading || history.loading) return <Loading />; if (current.error || history.error) return <Empty>First-touchdown predictions are unavailable.</Empty>; const record = history.data.record; return <><section className="hero"><p className="eyebrow">NFL FIRST-TOUCHDOWN MODEL</p><h1>First touchdown predictions</h1><p>One time-locked first-TD pick per game, selected from the highest-ranked anytime-TD candidate before kickoff.</p></section><div className="metric-grid"><article><p>First-TD record</p><b>{record.hits}-{record.misses}</b><small>HIT · MISS</small></article><article><p>Accuracy</p><b>{pct(record.accuracy)}</b><small>Graded official first-TD picks</small></article></div><h2>Current week</h2>{current.data.length ? <div className="table-wrap"><table><thead><tr><th>Matchup</th><th>First-TD pick</th><th>Team</th><th>Anytime TD probability</th><th>Kickoff</th></tr></thead><tbody>{current.data.map(pick => <tr key={pick.id}><td>{pick.away_team} @ {pick.home_team}</td><td className="accent">{pick.player_name}</td><td>{pick.team}</td><td>{pct(pick.anytime_probability)}</td><td>{easternTime(pick.date)}</td></tr>)}</tbody></table></div> : <Empty>First-TD picks publish with the next weekly touchdown run.</Empty>}<h2>History</h2>{history.data.predictions.length ? <div className="table-wrap"><table><thead><tr><th>Matchup</th><th>Pick</th><th>Team</th><th>Result</th></tr></thead><tbody>{history.data.predictions.map(pick => <tr key={pick.id}><td>{pick.away_team} @ {pick.home_team}</td><td>{pick.player_name}</td><td>{pick.team}</td><td className={pick.result === 'HIT' ? 'accent' : ''}>{pick.result}</td></tr>)}</tbody></table></div> : <Empty>No graded first-TD predictions yet.</Empty>}</> }
function NflPlayerStats() { const [query, setQuery] = useState(''); const [players, setPlayers] = useState([]); useEffect(() => { if (query.trim().length < 2) { setPlayers([]); return } api(`/nfl-players?query=${encodeURIComponent(query.trim())}`).then(setPlayers).catch(() => setPlayers([])) }, [query]); return <><section className="hero"><p className="eyebrow">NFL PLAYER STATISTICS</p><h1>Player season stats</h1><p>Completed regular-season totals only. Search any player by name.</p></section><div className="batter-search"><label>Search a player<input value={query} onChange={event => setQuery(event.target.value)} placeholder="Start typing a player name" /></label></div>{players.length ? <div className="table-wrap"><table><thead><tr><th>Player</th><th>Team</th><th>Total TD</th><th>Rush TD</th><th>Rec TD</th><th>Pass TD</th><th>Rush yards</th><th>Rec yards</th><th>Pass yards</th></tr></thead><tbody>{players.map(player => <tr key={player.player_id}><td className="accent">{player.player_name}</td><td>{player.team}</td><td>{player.total_touchdowns}</td><td>{player.rushing_touchdowns}</td><td>{player.receiving_touchdowns}</td><td>{player.passing_touchdowns}</td><td>{player.rushing_yards.toFixed(0)}</td><td>{player.receiving_yards.toFixed(0)}</td><td>{player.passing_yards.toFixed(0)}</td></tr>)}</tbody></table></div> : query.length >= 2 ? <Empty>No completed-game player stats found yet.</Empty> : null}</> }
function CfbTotals() { const data = useData('/cfb/predictions'); if (data.loading) return <Loading />; if (data.error) return <Empty>CFB totals are unavailable. Import FBS games, odds, train, and publish first.</Empty>; return <><section className="hero"><p className="eyebrow">FBS COLLEGE FOOTBALL TOTALS</p><h1>CFB Over / Under model</h1><p>FBS-vs-FBS games only. The model projects total points and compares them against the live market total.</p></section>{data.data.length ? <div className="table-wrap"><table><thead><tr><th>Matchup</th><th>Kickoff</th><th>Market total</th><th>Model total</th><th>Edge</th><th>Pick</th></tr></thead><tbody>{data.data.map(pick => <tr key={pick.id}><td>{pick.away_team} @ {pick.home_team}</td><td>{easternTime(pick.kickoff)}</td><td>{pick.market_total.toFixed(1)}</td><td>{pick.projected_total.toFixed(1)}</td><td className="accent">{margin(pick.edge)}</td><td className="accent">{pick.recommendation}</td></tr>)}</tbody></table></div> : <Empty>No FBS total predictions are published yet.</Empty>}</> }
function CfbHistory() { const data = useData('/cfb/history'); if (data.loading) return <Loading />; if (data.error) return <Empty>CFB totals history is unavailable.</Empty>; const { record, predictions } = data.data; return <><h1>CFB totals history</h1><p className="lede">Only FBS-vs-FBS locked total predictions are graded here.</p><div className="metric-grid"><article><p>Over / Under record</p><b>{record.wins}-{record.losses}-{record.pushes}</b><small>WIN · LOSS · PUSH</small></article></div>{predictions.length ? <div className="table-wrap"><table><thead><tr><th>Matchup</th><th>Market total</th><th>Model total</th><th>Pick</th><th>Actual total</th><th>Result</th></tr></thead><tbody>{predictions.map(pick => <tr key={pick.id}><td>{pick.away_team} @ {pick.home_team}</td><td>{pick.market_total.toFixed(1)}</td><td>{pick.projected_total.toFixed(1)}</td><td>{pick.recommendation}</td><td>{pick.actual_total.toFixed(0)}</td><td className={pick.result === 'WIN' ? 'accent' : ''}>{pick.result}</td></tr>)}</tbody></table></div> : <Empty>No graded CFB totals yet.</Empty>}</> }
function Methodology() { return <><h1>Methodology</h1><div className="method"><h2>Pregame only</h2><p>Every historical feature is calculated from information available before kickoff. Future results never enter a prior prediction.</p><h2>Model progression</h2><p>The platform begins with Elo, then tests logistic win probability and Ridge point-differential models on chronological splits.</p><h2>Market comparison</h2><p>American moneyline prices are normalized to no-vig probabilities before comparison. Outputs describe model disagreement, not betting instructions.</p></div></> }
function BatterSearch() {
  const [query, setQuery] = useState('')
  const [results, setResults] = useState([])
  const [projection, setProjection] = useState(null)
  const [message, setMessage] = useState('')
  useEffect(() => {
    if (query.trim().length < 2) { setResults([]); return }
    api(`/mlb/batters?query=${encodeURIComponent(query.trim())}`).then(setResults).catch(() => setResults([]))
  }, [query])
  const selectBatter = batter => {
    setQuery(batter.player_name)
    setResults([])
    setProjection(null)
    setMessage('Loading projection…')
    api(`/mlb/batters/${batter.player_id}/projection`).then(data => {
      setProjection(data.available ? data : null)
      setMessage(data.available ? '' : data.message)
    }).catch(() => setMessage('Projection is unavailable right now.'))
  }
  return <div className="batter-search"><label>Search a batter<input value={query} onChange={event => setQuery(event.target.value)} placeholder="Start typing a player name" /></label>{results.length ? <div className="search-results">{results.map(batter => <button key={batter.player_id} onClick={() => selectBatter(batter)}>{batter.player_name}<small>{batter.team}</small></button>)}</div> : null}{message ? <p className="lede">{message}</p> : null}{projection ? <article className="projection-card"><p className="eyebrow">EXPLORATORY PLAYER PROJECTION</p><h3>{projection.player_name}</h3><p>{projection.team} · {projection.game.away_team} @ {projection.game.home_team} · {easternTime(projection.game.first_pitch)}</p><b>{pct(projection.probability)}</b><span>Home-run probability</span><small>{projection.model_version} · Becomes official only after the confirmed-lineup publishing run.</small></article> : null}</div>
}
function MlbTopTen() {
  const top = useData('/mlb/top-10')
  if (top.loading || top.error) return null
  return <><h2>Today’s Top 10 HR probabilities</h2>{top.data.length ? <div className="table-wrap"><table><thead><tr><th>Rank</th><th>Player</th><th>Team</th><th>Matchup</th><th>HR probability</th><th>First pitch</th></tr></thead><tbody>{top.data.map((pick, index) => <tr key={`${pick.player_name}-${pick.game}`}><td>{index + 1}</td><td>{pick.player_name}</td><td>{pick.team}</td><td>{pick.game}</td><td className="accent">{pct(pick.probability)}</td><td>{easternTime(pick.first_pitch)}</td></tr>)}</tbody></table></div> : <Empty>No official Top 10 yet. It appears after confirmed-lineup predictions are published.</Empty>}</>
}
function MlbPerformance() {
  const performance = useData('/mlb/performance')
  if (performance.loading || performance.error) return null
  const data = performance.data.overall
  return <><h2>Model performance</h2>{data.predictions ? <><div className="metric-grid"><article><p>Official predictions</p><b>{data.predictions}</b><small>{data.hits} HIT · {data.misses} MISS</small></article><article><p>HR hit rate</p><b>{pct(data.hit_rate)}</b><small>Intuitive summary; not the only model metric.</small></article><article><p>Probability quality</p><b>{data.brier_score.toFixed(3)}</b><small>Brier · Log loss {data.log_loss.toFixed(3)}</small></article></div><h2>By model version</h2><div className="table-wrap"><table><thead><tr><th>Model</th><th>Picks</th><th>HIT / MISS</th><th>Brier</th><th>Log loss</th></tr></thead><tbody>{performance.data.by_model_version.map(row => <tr key={row.model_version}><td>{row.model_version}</td><td>{row.predictions}</td><td>{row.hits} / {row.misses}</td><td>{row.brier_score.toFixed(3)}</td><td>{row.log_loss.toFixed(3)}</td></tr>)}</tbody></table></div><h2>Daily results</h2><div className="table-wrap"><table><thead><tr><th>Date</th><th>Picks</th><th>HIT / MISS</th><th>Hit rate</th></tr></thead><tbody>{performance.data.daily.map(row => <tr key={row.date}><td>{row.date}</td><td>{row.predictions}</td><td>{row.hits} / {row.misses}</td><td>{pct(row.hit_rate)}</td></tr>)}</tbody></table></div></> : <Empty>Performance metrics will appear after official predictions have been graded.</Empty>}</>
}
function MlbGamePredictions() {
  const predictions = useData('/mlb/game-predictions')
  const performance = useData('/mlb/game-performance')
  if (predictions.loading) return <Loading />
  if (predictions.error) return <Empty>MLB game predictions are unavailable. Train and publish the MLB game model first.</Empty>
  const stats = performance.data
  return <><section className="hero"><p className="eyebrow">MLB QUANTITATIVE GAME MODEL · BETA</p><h1>MLB game predictions</h1><p>Pregame winner probabilities, projected margins, and market comparison.</p></section>{stats?.games ? <div className="metric-grid"><article><p>Winner accuracy</p><b>{pct(stats.accuracy)}</b><small>{stats.games} graded games · Brier {stats.brier_score.toFixed(3)}</small></article><article><p>Margin MAE</p><b>{stats.margin_mae.toFixed(2)}</b><small>RMSE {stats.margin_rmse.toFixed(2)}</small></article></div> : null}{predictions.data.length ? <div className="table-wrap"><table><thead><tr><th>Matchup</th><th>First pitch</th><th>Model winner</th><th>Model win %</th><th>Market win %</th><th>Difference</th><th>Model line</th><th>Market line</th></tr></thead><tbody>{predictions.data.map(prediction => { const homeFavorite = prediction.home_win_probability >= .5; return <tr key={prediction.game_id}><td>{prediction.away_team} @ {prediction.home_team}</td><td>{easternTime(prediction.first_pitch)}</td><td className="accent">{homeFavorite ? prediction.home_team : prediction.away_team}</td><td>{pct(prediction.home_win_probability)}</td><td>{pct(prediction.market_home_probability)}</td><td className="accent">{pct(prediction.moneyline_difference)}</td><td>{margin(prediction.predicted_home_margin)} {prediction.home_team}</td><td>{prediction.market_spread == null ? '—' : `${prediction.market_spread.toFixed(1)} ${prediction.home_team}`}</td></tr> })}</tbody></table></div> : <Empty>No upcoming MLB game predictions yet. Tomorrow, update the schedule and MLB odds, then publish the game predictions.</Empty>}</>
}
function MlbHistory() {
  const history = useData('/mlb/history')
  if (history.loading) return <Loading />
  if (history.error) return <Empty>MLB history is unavailable.</Empty>
  const data = history.data
  return <><section className="hero"><p className="eyebrow">MLB MODEL HISTORY</p><h1>Past predictions</h1><p>Predictions move here after first pitch and remain visible with their original model version and eventual result.</p></section><div className="metric-grid"><article><p>Game prediction record</p><b>{data.game_record.wins}-{data.game_record.losses}</b><small>WIN · LOSS</small></article><article><p>HR prediction record</p><b>{data.hr_record.hits}-{data.hr_record.misses}</b><small>HIT · MISS</small></article><article><p>Average probability of HR hits</p><b>{pct(data.hr_record.average_hit_probability)}</b><small>Average model probability among graded HIT picks</small></article></div><h2>Game predictions</h2>{data.game_predictions.length ? <div className="table-wrap"><table><thead><tr><th>Matchup</th><th>First pitch</th><th>Model winner</th><th>Home win %</th><th>Projected margin</th><th>Result</th><th>Model</th></tr></thead><tbody>{data.game_predictions.map(prediction => <tr key={prediction.id}><td>{prediction.away_team} @ {prediction.home_team}</td><td>{easternTime(prediction.first_pitch)}</td><td className="accent">{prediction.home_win_probability >= .5 ? prediction.home_team : prediction.away_team}</td><td>{pct(prediction.home_win_probability)}</td><td>{margin(prediction.predicted_home_margin)} {prediction.home_team}</td><td>{prediction.result || 'Pending'}</td><td>{prediction.model_version}</td></tr>)}</tbody></table></div> : <Empty>No past MLB game predictions yet.</Empty>}<h2>Home-run predictions</h2>{data.hr_predictions.length ? <div className="table-wrap"><table><thead><tr><th>Player</th><th>Team</th><th>Game</th><th>HR probability</th><th>Result</th><th>Model</th></tr></thead><tbody>{data.hr_predictions.map(prediction => <tr key={prediction.id}><td>{prediction.player_name}</td><td>{prediction.team}</td><td>{prediction.game}</td><td>{pct(prediction.probability)}</td><td>{prediction.result || 'Pending'}</td><td>{prediction.model_version}</td></tr>)}</tbody></table></div> : <Empty>No past MLB HR predictions yet.</Empty>}</>
}
function MlbOperations() {
  const status = useData('/mlb/status')
  const [selectedId, setSelectedId] = useState('')
  if (status.loading) return <Loading />
  if (status.error) return <Empty>MLB data is unavailable. Run the MLB update scripts, then refresh this page.</Empty>
  const data = status.data
  const selected = data.predictions.find(prediction => String(prediction.id) === selectedId)
  return <><section className="hero"><p className="eyebrow">MLB HOME-RUN MODEL · BETA</p><h1>MLB operations</h1><p>Completed-game ingestion, leakage-safe batter history, and versioned HR model training are kept separate from the NFL model.</p></section><div className="stat-grid"><div><b>{data.completed_games}</b><span>Completed games imported</span></div><div><b>{data.feature_rows}</b><span>Pregame batter feature rows</span></div><div><b>{data.scheduled_games.length}</b><span>Upcoming scheduled games</span></div></div><h2>Today’s schedule</h2>{data.scheduled_games.length ? <div className="table-wrap"><table><thead><tr><th>Matchup</th><th>First pitch</th><th>Probable pitchers</th></tr></thead><tbody>{data.scheduled_games.map(game => <tr key={game.id}><td>{game.away_team} @ {game.home_team}</td><td>{easternTime(game.first_pitch)}</td><td>{game.probable_away_pitcher || 'TBD'} / {game.probable_home_pitcher || 'TBD'}</td></tr>)}</tbody></table></div> : <Empty>No upcoming MLB games are currently loaded.</Empty>}<MlbTopTen /><h2>Latest model</h2>{data.models.length ? <div className="method"><p><b>{data.models[0].version}</b></p><p>Trained {easternTime(data.models[0].trained_at)} using completed games through {easternTime(data.models[0].training_data_through)}.</p></div> : <Empty>No MLB model has been trained yet.</Empty>}<h2>Search a batter</h2><BatterSearch /><h2>Official HR predictions</h2>{data.predictions.length ? <><label className="batter-picker">Select a published batter<select value={selectedId} onChange={event => setSelectedId(event.target.value)}><option value="">Choose a published prediction</option>{data.predictions.map(prediction => <option key={prediction.id} value={prediction.id}>{prediction.player_name || `Player ${prediction.player_id}`} · {prediction.team || 'Team unavailable'}</option>)}</select></label>{selected ? <article className="prediction-card"><p className="eyebrow">OFFICIAL HR PREDICTION</p><h3>{selected.player_name || `Player ${selected.player_id}`}</h3><p>{selected.team || 'Team unavailable'} · Game {selected.game_id}</p><b>{pct(selected.probability)}</b><span>Home-run probability</span><small>{selected.model_version} · {selected.result || 'Awaiting result'}</small></article> : null}<div className="table-wrap"><table><thead><tr><th>Game</th><th>Player</th><th>Team</th><th>HR probability</th><th>Model</th><th>Result</th></tr></thead><tbody>{data.predictions.map(prediction => <tr key={prediction.id}><td>{prediction.game_id}</td><td>{prediction.player_name || prediction.player_id}</td><td>{prediction.team || '—'}</td><td>{pct(prediction.probability)}</td><td>{prediction.model_version}</td><td>{prediction.result || 'Pending'}</td></tr>)}</tbody></table></div></> : <Empty>No official MLB HR predictions yet. Run the schedule and prediction scripts after both starting lineups appear in the MLB game feed.</Empty>}<MlbPerformance /></> }
function GameDetail({ id }) { const game = useData(`/games/${id}`); const predictions = useData(`/predictions/${id}`); if (game.loading || predictions.loading) return <Loading />; if (game.error) return <Empty>Game not found.</Empty>; return <><a className="back" href="/predictions">← Predictions</a><h1>{game.data.away_team} @ {game.data.home_team}</h1><p className="lede">Week {game.data.week} · {easternTime(game.data.date)}</p><PredictionTable predictions={predictions.data || []} games={[game.data]} /></> }
function App() { const path = window.location.pathname; const page = path.startsWith('/games/') ? <GameDetail id={decodeURIComponent(path.slice(7))} /> : path === '/predictions' ? <Predictions /> : path === '/elo-ratings' ? <EloRatings /> : path === '/touchdowns' ? <TouchdownPredictions /> : path === '/first-touchdowns' ? <FirstTouchdowns /> : path === '/touchdown-history' ? <TouchdownHistory /> : path === '/nfl-players' ? <NflPlayerStats /> : path === '/performance' ? <Performance /> : path === '/history' ? <History /> : path === '/cfb' ? <CfbTotals /> : path === '/cfb-history' ? <CfbHistory /> : path === '/mlb-games' ? <MlbGamePredictions /> : path === '/mlb-history' ? <MlbHistory /> : path === '/mlb' ? <MlbOperations /> : path === '/methodology' ? <Methodology /> : <Dashboard />; return <div className="shell"><aside><a className="brand" href="/"><span>NF</span> MODEL</a><nav>{nav.map(([href, label]) => <a className={path === href ? 'active' : ''} href={href} key={href}>{label}</a>)}</nav><p className="side-note">BETA V0.1<br />NFL + MLB</p></aside><main>{page}</main></div> }
createRoot(document.getElementById('root')).render(<App />)
